# 登录地址
url: http://119.61.22.194:2017/


# 登录账号密码
user:
  username: ET0502
  password: liangh24quan

# 查询的人员名称
name:
  - 梁皓
  - 王健壮
  - 徐康尊
  - 黄晓灿
  - 孙雯
  # - 周靖
  - 李帆
  # - 孙碧伯
  - 孙慧杰
  - 李胤杭
  # - 刘海岭
  - 郝志平
  # - 2025-05-20入职
  - 李晨

# 查询时间
select_data:
  stm: "2025-07-01"
  etm: "2024-07-31"

# 文件重命名
# 考勤合并文件Excel文件名
rename: 2025-08

# 文件存储路径
save_path:
    save_path1: "D:\\Elitel\\9_考勤统计\\2025-08考勤\\考勤明细"
    save_path2: "D:\\Elitel\\9_考勤统计\\2025-08考勤"
